		
all: mystat myls mytail mysearch
mystat: mystat-dang.c
	gcc -o mystat mystat-dang.c
myls: myls-dang.c
	gcc -o myls myls-dang.c
mytail: mytail-dang.c
	gcc -o mytail mytail-dang.c
mysearch: mysearch-dang.c
	gcc -o mysearch mysearch-dang.c
